# Generated by Django 3.2.7 on 2023-04-29 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RentalApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('rooms', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('rentalPeriod', models.CharField(max_length=30)),
                ('securityDeposit', models.CharField(max_length=30)),
                ('availableFrom', models.DateTimeField()),
                ('animalsAllowed', models.BooleanField()),
                ('monthlyRent', models.IntegerField()),
                ('furnished', models.BooleanField()),
                ('floor', models.IntegerField()),
                ('elevator', models.IntegerField()),
                ('balcony', models.BooleanField()),
                ('energyLabel', models.CharField(max_length=30)),
                ('parking', models.BooleanField()),
                ('moveInPrice', models.IntegerField()),
                ('prepaidRent', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.housetype')),
            ],
        ),
    ]
