# Generated by Django 3.2.7 on 2023-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='type',
            new_name='housingType',
        ),
        migrations.AddField(
            model_name='rentalapartment',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalapartment',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalapartment',
            name='garden',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalapartment',
            name='heading',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalapartment',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='balcony',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='elevator',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='furnished',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='parking',
            field=models.BooleanField(blank=True),
        ),
    ]
