# Generated by Django 3.2.7 on 2023-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20230430_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='heading',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
