# Generated by Django 3.2.7 on 2023-04-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20230430_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseType',
            new_name='apartmentType',
        ),
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='housingType',
            new_name='apartmentType',
        ),
    ]
