# Generated by Django 3.2.7 on 2023-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20230430_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='availableFrom',
            field=models.DateTimeField(null=True),
        ),
    ]
