# Generated by Django 3.2.7 on 2023-04-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_rentalapartment_availablefrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapartment',
            name='moveInPrice',
        ),
    ]
