# Generated by Django 3.2.7 on 2023-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_rentalapartment_moveinprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='balcony',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='elevator',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='furnished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='garden',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='parking',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
