# Generated by Django 3.2.7 on 2023-04-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20230430_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('rental_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.rentalapartment')),
            ],
        ),
    ]
