# Generated by Django 3.2.7 on 2023-05-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_apartmentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='apartmentType',
            new_name='type',
        ),
    ]
