# Generated by Django 3.2.7 on 2023-05-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_apartmenttype_rentalapartment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalsAllowed', models.CharField(max_length=255)),
                ('rental_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.rentalapartment')),
            ],
        ),
    ]
