# Generated by Django 3.2.7 on 2023-05-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_animalsallowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalsallowed',
            name='rental_apartment',
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='animalsAllowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.animalsallowed'),
        ),
    ]
