# Generated by Django 3.2.7 on 2023-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20230503_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='animalsAllowed',
            field=models.BooleanField(),
        ),
    ]
