# Generated by Django 3.2.7 on 2023-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_rentalapartment_animalsallowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='animalsAllowed',
            field=models.BooleanField(),
        ),
    ]
