# Generated by Django 3.2.7 on 2023-05-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_rentalapartment_animalsallowed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalsAllowed',
        ),
    ]
