# Generated by Django 3.2.7 on 2023-05-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_delete_animalsallowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='animalsAllowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.animalsallowed'),
        ),
    ]
