# Generated by Django 3.2.7 on 2023-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20230510_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='availableFrom',
            field=models.DateField(auto_now_add=True),
        ),
    ]
