# Generated by Django 3.2.7 on 2023-05-10 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0018_alter_rentalapartment_availablefrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='animalsAllowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.animalsallowed'),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='availableFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.apartmenttype'),
        ),
    ]
