# Generated by Django 3.2.7 on 2023-05-10 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20230510_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='availableFrom',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
    ]
