# Generated by Django 3.2.7 on 2023-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_rentalapartment_availablefrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='availableFrom',
            field=models.DateTimeField(null=True),
        ),
    ]
