# Generated by Django 3.2.7 on 2023-05-13 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0023_alter_rentalapartment_availablefrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalapartment',
            old_name='User',
            new_name='user',
        ),
        migrations.CreateModel(
            name='SavedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rentalApartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.rentalapartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
