# Generated by Django 3.2.7 on 2023-05-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20230513_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='size',
            field=models.IntegerField(max_length=30),
        ),
    ]
