# Generated by Django 3.2.7 on 2023-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_alter_rentalapartment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='size',
            field=models.IntegerField(),
        ),
    ]
