# Generated by Django 3.2.7 on 2023-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalapartment',
            name='size',
            field=models.IntegerField(max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
