# Generated by Django 3.2.7 on 2023-05-25 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0031_auto_20230524_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedapartment',
            unique_together={('user', 'rentalApartment')},
        ),
    ]
