# Generated by Django 3.2.7 on 2023-05-26 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0032_alter_savedapartment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapartment',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='savedapartment',
            unique_together={('rentalApartment', 'user')},
        ),
        migrations.CreateModel(
            name='ReportApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('rentalApartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.rentalapartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rentalApartment', 'user')},
            },
        ),
    ]
