# Generated by Django 3.2.7 on 2023-05-28 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0033_auto_20230526_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rentalApartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.rentalapartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rentalApartment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReportRentalApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rentalApartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.rentalapartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rentalApartment', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ReportApartment',
        ),
    ]
