# Generated by Django 3.2.7 on 2023-06-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_auto_20230528_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentimage',
            name='image',
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='images',
            field=models.FileField(default='d', upload_to='images/'),
            preserve_default=False,
        ),
    ]
