# Generated by Django 3.2.7 on 2023-06-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
