# Generated by Django 3.2.7 on 2023-06-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
