# Generated by Django 3.2.7 on 2023-06-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapartment',
            name='city',
        ),
    ]
